add the reformulated version of Fiedler_BMCSystBiol2016
Benchmarking-Initiative/Benchmark-Models-PEtab pull request #258
Opened 2024-12-04 14:50 UTC by m-philipps

- closes issue #252 
- add reformulated version of the existing `Fiedler_BMCSystBiol2016` model, taken from the same publication, that removes non-identifiabilities
- add a `datasetId` column for the existing `Fiedler_BMCSystBiol2016` model

2024-12-04 15:32 UTC, FFroehlich commented
would assume that all of the data is the same – why not just add separate model/parameters/yaml file to the base directory and reuse everything else?

2024-12-17 19:03 UTC, m-philipps commented
The data is the same, the observable Ids changed (e.g. `pErk` -> `pErk_rel`) and that is propagated through the noise and observable parameters. Only the experimental condition files are the same.

I could rename the observables and associated parameters but I have a minor preference for keeping the new names to distinguish the interpretation of the observables in the old and reformulated model.

2025-01-04 16:59 UTC, dilpath requested changes
Looks good. Since this is similar to submitting a new problem, you could add the checklist to this PR and indicate what is done/not done (of course, not everything has to be done since this is not the "main" problem -- simply leave those unchecked as a matter of record).

2025-01-04 16:59 UTC, dilpath commented on Benchmark-Models/Fiedler_BMCSystBiol2016/measurementData_Fiedler_BMCSystBiol2016.tsv
The corresponding simulatedData file is now missing the datasetId column.

2025-01-04 16:59 UTC, dilpath commented on Benchmark-Models/Fiedler_BMCSystBiol2016/reformulated/parameters_Fiedler_BMCSystBiol2016.tsv
> +s_pMek_rel_20140430_gel1	s_{pMek_rel,20140430,gel1}	log10	1E-04	1E02	9.113038276921857	1
I guess these won't render nicely in latex, but fine to leave as is.
```suggestion
s_pMek_rel_20140430_gel1	s_{pMek_{rel},20140430,gel1}	log10	1E-04	1E02	9.113038276921857	1
```

2025-01-04 16:59 UTC, dilpath commented on Benchmark-Models/Fiedler_BMCSystBiol2016/reformulated/Fiedler_BMCSystBiol2016.yaml
Use a different ID than `Fielder_BMCSystBiol2016` to distinguish it from the original problem. Can be anything, e.g. `Fielder_BMCSystBiol2016_rel`

2025-01-04 16:59 UTC, dilpath commented on Benchmark-Models/Fiedler_BMCSystBiol2016/reformulated/model_Fiedler_BMCSystBiol2016.xml
Change the model ID to reflect the different PEtab problem ID (e.g. `Fielder_BMCSystBiol2016_rel`). I guess this will also allow users to compile both the original and reformulated variants with AMICI and use them side-by-side without having to define custom compilation folders.

2025-01-04 19:28 UTC, m-philipps commented
- [x] The PEtab problem is based on a model that is peer-reviewed and published
- [ ] The problem ID is in the format `{LAST_NAME_OF_FIRST_AUTHOR}_{ABBREVIATED_JOURNAL_NAME}{YEAR_OF_PUBLICATION}` 
$\to$ No, `Fiedler_BMCSystBiol206` already exists, ID is `Fiedler_BMCSystBiol206_rel` 
- [ ] The problem ID is in the pull request title
- [x] There is a GitHub issue for this problem
  - [ ] The problem ID is in the issue title
  - [ ] A brief model description (one or two sentences)
  - [ ] A brief data description (one or two sentences)
  - [x] The issue and PR are linked to each other
  - [ ] Differences between the implementation and the original publication are described
  - [x] Experience of fitting / uncertainty analysis (e.g. optimizer used, hyperparameters, reproducibility of best fit)
  - [x] Source of nominal parameters (e.g.: taken from the original publication, or from your own fitting)
- [x] The SBML file
  - [x] Annotation with reference to the original publication ([example](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/3154d27edbfc4eb19b768465945bc81381a7c964/Benchmark-Models/Rahman_MBS2016/model_Rahman_MBS2016.xml#L4-L14))
  - [x] The model ID and model name attributes in the SBML model file match the problem name ([example](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/3154d27edbfc4eb19b768465945bc81381a7c964/Benchmark-Models/Rahman_MBS2016/model_Rahman_MBS2016.xml#L3))
- [x] PEtab files
  - [x] A "simulated data" measurement table is included, using the nominal parameters
  - [ ] A visualization table is included, that can be used with the simulated data to reproduce figures from the original publication
  - [x] The PEtab problem is valid (check with e.g. `petablint -vy problem.yaml`)
- [x] The PEtab problem author(s) are assigned to the GitHub issue
- [x] The README has been updated with `bmp-create-overview  --update` (requires `pip install -e src/python/bmp` from the repository root)
  - [ ] The new PEtab problem row in the generated table has the correct reference (and other entries)

2025-01-04 20:10 UTC, dilpath commented
>   * [x]  Annotation with reference to the original publication ([example](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/3154d27edbfc4eb19b768465945bc81381a7c964/Benchmark-Models/Rahman_MBS2016/model_Rahman_MBS2016.xml#L4-L14))

I think this is missing, but also fine to uncheck this box instead.

2025-01-04 20:11 UTC, dilpath approved these changes

2025-01-04 21:49 UTC, merged